apiVersion: v1
kind: Service
metadata:
  name: nginxweb
  labels:
    app: nginxweb
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginxweb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginxweb # has to match .spec.template.metadata.labels
  serviceName: "nginxweb"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: nginxweb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginxweb
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
